@startuml construcktor
start 
:Get Os;
if (GNU/Linux or BSD) then (yes)
	:set Unix home dir;
	:set linux pdflatex bin path;
elseif (Windows) then (yes)
	:set windows home dir;
	:set windows pdflatex bin path;
elseif (mac) then (yes)
	:set mac home dir;
	:set mac pdflatex bin path;
endif
stop
@enduml