#!/usr/bin/sh

#buildcommand="make clean"
buildcommand="make clean"
buildcommand="mvn clean package javadoc:javadoc javadoc:aggregate"

$buildcommand && notify-send --icon=gtk-info "Build has completed" || notify-send --icon=gtk-info "Build has failed"
