@startuml cli

skinparam monochrome true

package de.thowl.aids.cli {
	class Main {
		- {static} logger: Logger
		- {static} type: String
		- {static} destination: String
		- {static} amount: int
		- {static} chapters: int
		- {static} shuffle: boolean;
		+ {static} main(String[]: args): void
		- {static} formatArg(String: arg): String
		- {static} handleArgs(String[]: args): void
		- {static} handleParamArgs(String: arg, String: prevArg): void
		- {static} checkInt(String: inputInt): int
		- {static} printVersion(): void
		- {static} printHelp(): void
	}
}

@enduml

@startuml Main
skinparam monochrome true
start
:Count Arguments;
if (No Argumants) then (yes)
	:Start Gui;
	stop
else
	:Handle Arguments;
	:Generate Document(s);
endif
stop
@enduml

@startuml formatArg
skinparam monochrome true
start
:take arg;
:remove dashes;
:return arg;
stop
@enduml

@startuml handleArgs
skinparam monochrome true
start
while (argumnets)
        if (If valid argument) then (yes)
	        :run corresponding method;
	        stop
        else
	        :pass to handle param args;
        endif
stop
@enduml

@startuml handleParamArgs
skinparam monochrome true
start
while (argumnets)
        :save arg;
        :get param;
        if (If valid argument) then (yes)
	        :run corresponding method with param;
        endif
stop
@enduml
