@startuml gatherSnippets
skinparam monochrome true
start
:Get Latex Header path;
:Construct latex header Object;
while (filelist?) is (incomplete)
    :get filepath from database;
    :construct file;
    :add file to list;
endwhile (contains all files)
:Get latexfooter path;
:Construct latex footer Object;
stop
@enduml

@startuml concat
skinparam monochrome true
start
:Initialise file;
:Append Latexheader content to file;
:Fromat Latexsnipptet filepath and append to file;
:Append Latexfooter content to file;
:Print file content fo disk;
stop
@enduml

@startuml compile
skinparam monochrome true
start
:construct pdflatex command;
:execute command;
stop
@enduml
