@startuml de.thowl.aids.database
package de.thowl.aids.database {
        class MySQL{
                - url: String
                - userName: String
                - password: String
                - con: Connection
                + openConnection: void
                + closeConnection: void
                + getSubjekt: String
                + setSubjekt: String
        }
}
@enduml
